name: Build and Publish Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Where am i
      run: |
        pwd

    - name: Build Debian package
      run: |
        cd homelab/role/build/files/homelab-blackbox-exporter_amd64
        dpkg-buildpackage -us -uc

    - name: Publish package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DEB_FILE=$(ls homelab-blackbox-exporter_amd64*.deb)
        echo "Publishing $DEB_FILE to GitHub Packages..."
        
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @homelab/role/build/files/$DEB_FILE \
          "https://uploads.github.com/repos/khaddict/homelab/packages/deb/ubuntu/${{ github.ref_name }}/$DEB_FILE"
