name: Build and Publish Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts dh-make curl

    - name: Build Debian package
      run: |
        cd role/build/files/homelab-blackbox-exporter_amd64
        dpkg-buildpackage -us -uc

    - name: List generated .deb files
      run: ls role/build/files/*.deb

    - name: Publish package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DEB_FILE=$(ls role/build/files/homelab-blackbox-exporter_*_amd64.deb | head -n 1)
        echo "Publishing $DEB_FILE to GitHub Packages..."
        
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @$DEB_FILE \
          "https://uploads.github.com/repos/khaddict/homelab/packages/debian/${{ github.sha }}/$(basename $DEB_FILE)"
